version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  build2:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world222222.
         

workflows:
  version: 2
  build:
    jobs:
      - build:
           filters:
            tags:
              only: /.*/
      - build2:
           filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
